server:
  port: 8015
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
        # 是否和服务注册与发现组件结合，设置为 true 后可以直接使用应用名称调用服务
          enabled: true
      # 路由规则
#      routes:
#        - id: user-service
#          # lb代表从注册中心获取服务，且以负载均衡方式转发
#          uri: lb://biz-user-service
#          predicates:
#            - Path=/user/**
#          # Gateway默认转发是全路径的（即StripPrefix=0）。假如设置StripPrefix=2表示从二级url路径转发，即http://{localhost}:{port}/user/bar/foo，去除掉url前面两个前缀之后，最后转发到目标服务的路径为http://{biz-user-service}/foo
#          filters:
#            - StripPrefix=0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9110/eureka

